version: '3.6'
services:
  java:
    container_name: java-low
    build: .
    volumes:
      - ./:/app
    command: mvn -f /app/pom.xml spring-boot:run
    depends_on:
      - postgresql
    ports:
      - 9090:9090
  postgresql:
    container_name: java-postgresql
    image: postgres
    environment:
      - POSTGRES_DB=docker
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: {}